#
# Module manifest for module 'Pode.Ldap'
#
# Generated by: Matthew Kelly (Badgerati)
#
# Generated on: 11/12/2019
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'Pode.Ldap.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # ID used to uniquely identify this module
    GUID = '21678d4b-14dc-4a8c-91fd-e61350aac18f'

    # Author of this module
    Author = 'Matthew Kelly (Badgerati)'

    # Copyright statement for this module
    Copyright = 'Copyright (c) 2019 Matthew Kelly (Badgerati), licensed under the MIT License.'

    # Description of the functionality provided by this module
    Description = 'An LDAP Authnetication extension module for the Pode web server (v1.3.0+)'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('powershell', 'powershell-core', 'windows', 'unix', 'linux', 'PSEdition_Core',
                'PSEdition_Desktop', 'cross-platform', 'ldap', 'pode', 'active-directory')

            # A URL to the license for this module.
            LicenseUri = 'https://raw.githubusercontent.com/Badgerati/Pode.Ldap/master/LICENSE.txt'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Badgerati/Pode.Ldap'

        }
    }
}